version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: ruby:2.4.0
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake
